name: PHP_CI_PCGALAXY

on:
  push:
    branches:
      - auto-test-4
  pull_request:
    branches:
      - auto-test-4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit tests
